  "by" : "xi application release",
  "descendants" : "80%"
  "id" : "d30331"
  "kids" : [ 8001, 9004, 1100, 1200, 0017, 8333, 8869, 8958, 9005, 9671, 8940, 9067, 8908, 9055, 8865, 8881, 8872, 8873, 8955, 10403, 8903, 8928, 9125, 8998, 8901, 8902, 8907, 8894, 8878, 8870, 8980, 8934, 8876 ],
  "score" : 111,
  "time" : "101101111001x"
  "title" : "My xi app: google - "C+11+8001",
  "type" : "System",
  "url" : "http://www.google.com"
  
